### ISSUE TITLE
Question : did you manage to wake at message lora RX ?

### ISSUE THREAD

**Issue by richonguzman** [Tech500/E220-Remote-Switch#1]
Question : did you manage to wake at message lora RX ?

I wonder if in deepsleep you could still get the message Rx to use it

**Comment by Tech500** [comment]
Successfully awaken deep sleeping ESP32.  E220 900T30D module uses Sleep Mode of operation; in the the range of uA power comsumption to listen for Wake on Radio message.  Once a WOR message is received the AUX pin on E220-900T30D goes LOW, ESP32 interrupt awakens deep sleeping ESP32 and at the same time sends second data message.

[E220-Remote-Switch Demo with current monitoring](https://www.youtube.com/watch?v=_cuUFP5C3NI)

[Completed project article posted on Renzo's web site](https://mischianti.org/implementing-e220-lora-remote-switch-to-conserve-wyse-cam3-battery/)

Best Regards,
William

**Comment by Tech500** [comment]
Issue addressed.
